version: '3.1'

services:
  content_service:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - content_service
    ports:
      - "8080:8080"

networks:
  content_service:
    external: true