version: '3.1'

services:
  prometeus_service:
    image: prom/prometheus:v2.43.1
    restart: always
    volumes:
      - ./local_prometeus/prometeus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./local_db/data:/var/lib/postgresql/data
      - ./local_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: content
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pa55word
    networks:
      - content_service

networks:
  content_service:
    external: true