openapi: 3.0.3
info:
  version: 1.0.0
  title: Content
servers:
  - url: http://localhost:8080
tags:
  - name: Categories
    description: Category related endpoints
  - name: Posts
    description: Posts related endpoints
  - name: Template
    description: Template related endpoints
components:
  schemas:
    "category":
      properties:
        id:
          type: integer
          required: false
        name:
          type: string
          required: true
        tenant_id:
          type: integer
          required: true
    "idWrapper":
      properties:
        id:
          type: integer

paths:
  /category:
    post:
      tags:
        - Categories
      description: Route for creating a category
      requestBody:
        description: Category body
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/category"
      responses:
        201:
          description: Category created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/idWrapper"
        400:
          description: Validation error, either your body isn't correct or the category already exists
        500:
          description: Category cannot be created
